-  name: demo on data types
   hosts: local
   connection: local
   vars: 
     PROGRAM: "DevSecOps with AWS"
     DURATION: 140
     IS_LIVE: true
     DETAILS:
       MONTHS: 4 
       TRAINER: "Sivakumar Reddy"
     TOPICS:
       - linux
       - shell
       - ansible 
   tasks: 
    - name: print variables
      ansible.builtin.debug:
       msg: 
        program: {{ PROGRAM }}
        duration: {{ DURATION }}
        is live : {{ IS_LIVE }}
        details: {{ DETAILS }}
        topics: {{ TOPICS }}    
